version: "3.7"
services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
  
  app:
    build: app
    restart: always
    secrets:
      - db-password
    ports:
      - 5000:5000
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
